### ISSUE TITLE
MVP Documentation @ https://kids-first.github.io/kf-lib-data-ingest/

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#108]
After the last MVP extract stage functionality is complete (#93 and #107), we really should take a pause on development and focus on populating our docs site with some MVP documentation. 

Even though the entire pipeline has not been implemented yet we should do MVP documentation which includes:

- An overview of the ingest library - purpose, the pieces and parts 
- A quick start example as if the ingest library is complete - we can leave blanks and fill in later
- Complete extract stage documentation

There are two reasons for doing MVP docs now:
1. Extract stage is at a point where it can be used by data wranglers. If we can provide a quick start example along with API level documentation for extract stage only, then this will be enough for a data wrangler to independently go off and start using the ingest library.

2. If we can provide some documentation on what the ingest library is, how its intended to work, etc  then it will be easier to get other devs involved to finish the lib if that is desired. Also, it will serve as educational material in preparation for using the library in the accounting system.

**Comment by fiendish** [comment]
progress in #109
