### ISSUE TITLE
Quickstart for ingest docs

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#116]
I really like the way Django rest framework does their documentation. They have both a quick start example that gets you up and running with a simple API and a full in depth tutorial. The quick start is focused on using Django rest framework and showing you the end result rather than on how the framework works. 

See https://www.django-rest-framework.org/tutorial/quickstart/

We should have a quickstart example for the ingest that does the same. It would be great to even have a special CLI command that generates the full ingest project folder for you with both the study configuration and the simple source data:

```shell

$ kidsfirst quickstart
``` 

Generates for you everything you need for the quick start tutorial:

```
    My_Study/
    ├── dataset_ingest_config.yml
    ├── extract_configs/
    │   └── clinical_data.py
    ├── transform_module.py
    └── data/
        └── clinical_data.tsv
```
The quick start tutorial should show you how to:
- Modify the extract config
- Modify the transform_module.py
- Run ingest
- View outputs and logs

**Comment by fiendish** [comment]
>     └── data/
>        └── clinical_data.tsv

Not sure if it should generate this or link to a remote file from the config.

**Comment by fiendish** [comment]
This is done, yes?

**Comment by znatty22** [comment]
No, not done yet. We have our `kidsfirst new` command that basically generates the package needed to get started quickly, but now we need to write up the docs in the quickstart section.

**Comment by fiendish** [comment]
I thought we have docs

**Comment by znatty22** [comment]
we're missing this section tho: https://kids-first.github.io/kf-lib-data-ingest/quickstart.html
