### ISSUE TITLE
Need constant defined for affected_status of participant

### ISSUE THREAD

**Issue by parimalak** [kids-first/kf-lib-data-ingest#125]

**Comment by fiendish** [comment]
Give me a description of what "affected_status" means, please

**Comment by parimalak** [comment]
affected_status is a boolean field which specifies whether the participant is affected.

**Comment by fiendish** [comment]
affected by what

**Comment by parimalak** [comment]
diagnosis or phenotype

**Comment by fiendish** [comment]
I don't understand. If a participant has a diagnosis then they have a diagnosis. Phenotypes are observed negative or positive. Which part are we missing?

**Comment by parimalak** [comment]
affected_status is provided by investigator as affected_child or affected. For example if study has `Cancer` as diagnosis_category; mostly all Probands are are affected, and also got at least one family with other family relationship diagnosed with the same disease. For structural birth defect example, consider cleft lip and cleft palate; affected_status is true for participant with anyone in the family who has the same phenotype. phenotype observed is based on the observations provided by the investigator. participants can have multiple phenotypes and diagnosis associated with them. but affected_status captures if participants have same diagnosis/phenotype for that study.

**Comment by fiendish** [comment]
👍
