### ISSUE TITLE
🐛df[df.isna()] = None does not seem to work

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#147]
Doesn't seem to work. I don't know why. But this works: `df = df.where((pandas.notnull(df)), None)`

Solution found here: https://stackoverflow.com/questions/14162723/replacing-pandas-or-numpy-nan-with-a-none-to-use-with-mysqldb

**Comment by fiendish** [comment]
ugh. oops. I could have sworn...
