### ISSUE TITLE
Should previous output of stage be cleared before writing new output?

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#169]
Right now we run ingest and and each stage writes its output without clearing out any previously stored output. Should each stage clear its existing output before writing new output?

**Comment by fiendish** [comment]
I could see maybe an overwrite_output flag in the study config like we have overwrite_log

**Comment by znatty22** [comment]
What should be the default behavior?

**Comment by fiendish** [comment]
I guess...

(I'm assuming here that a log without the corresponding output isn't super useful)

Change `overwrite_log` to `preserve_output`.

Declare that the ideal output subdirectory structure is:

```
study/
  output/
     Stage1/
     Stage2/
     ...
     ingest.log
     archive/
```

If `preserve_output ` is `True`, after ingest ends/aborts, make a new datestamped folder in study/output/archive/ and then copy everything in study/output/ except for archive/ into archive/<stamped_folder>/

**Comment by fiendish** [comment]
Side note: the current date stamps on the ingest log files use forward slashes. That will break a lot of file systems. Notably vscode has a hack in it to convert forward slashes in file names to colons, because it's only really supported on macOS.

**Comment by znatty22** [comment]
Yes, but only if it is easy (in Python) to convert from ISO 8601 "basic" format strings back to regular ISO 8601 so that we can easily get the pieces and parts of the timestamp

**Comment by fiendish** [comment]
`datetime.datetime.fromisoformat(datetime.datetime.now().isoformat())` works fine

**Comment by fiendish** [comment]
```Python
TIME_FORMAT = '%Y%m%dT%H%M%S'
a = datetime.datetime.now().replace(microsecond=0)  # microseconds is silly
b = datetime.datetime.strptime(a.strftime(TIME_FORMAT), TIME_FORMAT)
a == b
```

**Comment by znatty22** [comment]
We like current behavior. Closing this issue.
