### ISSUE TITLE
Use "ingest package" as the official term for describing the ingest configuration dir

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#170]
The docs and comments refer to the directory where all ingest configuration is stored in different ways. Sometimes we say ingest config dir, other times we say study config dir, and in the docs we mostly say "ingest module".

I think this directory should formally be called the "ingest package". I would define it as the directory containing all necessary configuration files needed to ingest a dataset using the kf-lib-data-ingest library.

**Comment by fiendish** [comment]
seems reasonable

**Comment by fiendish** [comment]
this is done, yes?

**Comment by znatty22** [comment]
Not quite. We've renamed things in the docs, but our code still uses different terms. We should probably call the `dataset_ingest_config.py` file `ingest_package_config.py`.
