### ISSUE TITLE
Discuss accounting requirements with stakeholders

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#175]
We put the initial high level reqs in https://github.com/kids-first/kf-lib-data-ingest/blob/master/docs/design/accounting.md
but we need to discuss this with our stakeholders and ensure we're all on the same page. 

The default accounting tests (entity counts, relationship counts) seem to be agreed upon, but the configurability of the tests (on/off switch, custom tests, etc) has not been agreed upon. 

Current PR is: #144

**Comment by fiendish** [comment]
Comment thread is in #145

**Comment by znatty22** [comment]
The takeaways from our conversation were:

**Accounting Stuff**
- Do implement a standard set of accounting tests that will run for every study
- Do - allow implementation of custom tests per study
- Do - allow plugin of custom test via configuration
- Do - have a `debug_mode` flag that runs all stages of ingest and accounting tests BUT does not actually send POST/PATCH requests to the target service
- Get rid of the `--strict_accounting` flag on ingest CLI. Accounting is purely informative and will always run when ingest runs. Ingest will never abort on accounting test failures.

**Other Things**
- When the test runner invokes ingest for packages in `ingest.yaml` run with `kidsfirst ingest <path to ingest package> --debug_mode` 
- Do nightly regression testing for kf-lib-data-ingest by running ingest in `debug_mode` for all ingest packages in `kf-ingest-packages/kf_ingest_packages/packages`.
Nightly test runner on kf-lib-data-ingest library, run ingest on all ingest packages
- Once we start using the new ingest system, do not change existing studies in dataservice, just make temp study kf ids for the ingestions
