### ISSUE TITLE
(Proposal) refactor to eliminate transform/common?

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#177]
Issue:

There's a funny transform/common file with some functions that are used collectively by transform but which doesn't natively share the same namespace.

Proposal: 

Restructure the transformers so that they inherit from TransformStage as the shared common base instead of being inserted into it

Exact steps needed (I'm pretty sure):
1. Make AutoTransformer and GuidedTransformer inherit TransformStage and rename them to AutoTransformStage and GuidedTransformStage
2. Rename AutoTransformStage.run and GuidedTransformStage.run to _do_transform
3. Add _do_transform as an abstract base method to TransformStage (just for fun)
4. Make TransformStage._run call `target_instances = self._do_transform(data_dict)` in place of         `insert_unique_keys(data_dict); target_instances = self.transformer.run(data_dict)`
5. Make AutoTransformStage._do_transform and GuidedTransformStage._do_transform responsible for their own calls to insert_unique_keys.
6. Put insert_unique_keys into TransformStage instead of transform/common.py so that it can share the stage identity when logging
7. Replace the logger invocations in the methods moved from transform/common.py with self.logger
8. Remove the `if not transform_function_path else` section from TransformStage.\_\_init\_\_ and move the check to where `self.stage_dict['t']` is in ingest_pipeline to instantiate either a GuidedTransformStage or an AutoTransformStage instead of just a TransformStage

I didn't actually test the steps to ensure that it's the full set of needed changes, but by eyeballing it seems right

**Comment by znatty22** [comment]
I think that should work .. I can address this after we complete our first working version of the transform stage
