### ISSUE TITLE
Add a new standard concept attribute called SOURCE_UID and use it instead of ID

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#178]
When we map a column in the source data to `CONCEPT.<something>.ID`, we're really mapping a unique identifier assigned from the source/data provider to some value that uniquely identifies the concept in the source data. 

Let's be more specific in the concept schema and have SOURCE_UID as an attribute. We could either replace ID or just add a new attribute for SOURCE_UID. But do we really need something called ID - what is that anyway?

Then, we should also update all of our tests and any extract configs that use the ID attribute.
If we replace the ID attribute this will be a breaking change to users of the lib.

cc @parimalak

**Comment by fiendish** [comment]
Are you not talking about UNIQUE_KEY?

**Comment by znatty22** [comment]
No not UNIQUE_KEY. This is about renaming the ID concept attribute to `SOURCE_UID` so that is more clear that its the unique identifier assigned by the data contributor in the source data. And then I believe I have another similar issue https://github.com/kids-first/kf-lib-data-ingest/issues/179 thats about renaming `UNIQUE_KEY` to `SYNTHETIC_UID` so that its more clear that this is a sythetic/ingest made up unique identifier for a concept.

If we're serious about renaming things, we should really do it soon so that we don't have to update a bunch of ingest packages later...

**Comment by fiendish** [comment]
any updates will all just be bulk find/replace. using variables instead of strings means it can be done safely.

**Comment by znatty22** [comment]
Well I think I want to rename variables too even more so than the values.. Personally, I think the proposed new variable names (`SOURCE_UID`, `SYTHETIC_UID`) are more intuitive to both an ingest package dev and a new/unknowing ingest library developer.

**Comment by fiendish** [comment]
Yeah that's fine. The reason it's safe to use find and replace is because we're using variables and not plain strings.

**Comment by znatty22** [comment]
Closing because this will change once we decide to refactor the concept schema. Not worth it to rename anything now.
