### ISSUE TITLE
Preserve original file's extension when fetching file

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#183]
Currently the file retriever downloads the file's data to the temporary file object but does not preserve the original file extension. 

Everything has been working fine in extract stage because it uses the original `source_data_url` from the extract config to inspect file extension and choose a load_func, rather than the file extension of the fetched file. This works for everything except http type download URLs which don't contain the actual filename in the URL:
`http://localhost:8080/download/study/SD_00001111/file/SF_4H3NRQH4`

**Comment by fiendish** [comment]
Question: Do we actually need to name the temp file, or is it sufficient to set a original_name member on the returned data object?
