### ISSUE TITLE
Add Dry Run Mode for Ingest Pipeline

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#186]
@fiendish writing up your original idea in an issue ...

We should have a CLI option called something like `dry_run`. When supplied it will cause the ingest pipeline to execute all stages normally except for the load stage. During dry run mode the load stage would not actually send requests to the target service to modify data.

This mode of operation would be used to by:
- the ingest package developer while developing an ingest package for a dataset
- the CI system in https://github.com/kids-first/kf-ingest-packages to perform automated testing for ingest packages

**Load Stage Behavior:**

Note - UID cache (keeps a mapping of the unique id of the entity in the source data to the id assigned to entity by the target service) 

**Create new entity in target service**

Normal operation 
- Send POST with entity payload to the target service
- Update the UID cache with the new record of entity UID from source data, entity ID assigned by target service

Dry run operation
- Write the POST payload to the load stage output 
- Do not update UID cache

**Update existing entity in target service**

Normal operation
- Send PATCH with updated entity payload to the target service

Dry run operation
- Lookup entity's target service ID in UID cache
- Send GET to fetch entity from target service
- Update the entity payload from the GET response
- Save modified payload to load stage output

If someone looks at the load stage output from dry_run mode, they should see a preview of almost exactly what the data to be ingested would look like in the target service.

**Comment by fiendish** [comment]
> Dry run operation
>
> Send GET to fetch entity from target service

This isn't needed. You already have the entity data in memory.
