### ISSUE TITLE
dataservice fails harder than we thought sometimes

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#204]
I want to up retry counts because retrying is free. Ran into a problem the other day where the dataservice fell over for kind of a long time before coming back up.

**Comment by allisonheath** [comment]
It's free, but if the service is down because of load, exponential backoff might be a good idea

**Comment by fiendish** [comment]
We _do_ exponential backoff.

**Comment by allisonheath** [comment]
Excellent - didn't get a chance to actually look at it 👍
