### ISSUE TITLE
visible==HIDDEN in kf_lib_data_ingest/target_apis/kids_first.py

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#218]
The mapping for visible fields are all backwards. visible is _not_ hidden.

**Comment by znatty22** [comment]
Do you want to keep the `CONCEPT.<something>.HIDDEN` attribute as is? Or should we make it `CONCEPT.<something>.VISIBLE`. Then we don't have to do this everywhere in the kids_first.py target api config:

```
'family': {
        'properties': {
            'visible': not CONCEPT.FAMILY.HIDDEN,
             ...
        }
    },
    'participant': {
        'properties': {
            'visible': not CONCEPT.PARTICIPANT.HIDDEN,
             ...
        },
    },
```

**Comment by znatty22** [comment]
👍
