### ISSUE TITLE
extend expected_counts configuration to include values

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#232]
Currently expected_counts includes something like e.g. `{'PARTICIPANT.ID': 5}`

We should extend it to do also something like `{'PARTICIPANT.SEX': {'Female': 5, 'Male': 4}}`

**Comment by fiendish** [comment]
Details to consider: what does it mean to say that 5 instances of sex=Female were found during the extract stage if there are multiple files with overlapping sets of participant data? We probably need to link non-identifying keys to identifying keys. Like for instance, "there are 5 PARTICIPANT.ID where PARTICIPANT.SEX is Female in the same row."

**Comment by znatty22** [comment]
Closing because this will be replaced with the new validation that will be implemented soon
