### ISSUE TITLE
token auth header uses the term "Token" instead of "Bearer"

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#260]
JWT tokens should use the descriptor Bearer

**Comment by znatty22** [comment]
Heh I could've sworn study creator used `Token` before

**Comment by fiendish** [comment]
It might have.
It doesn't work either way, so this change will have no real effect until the api is fixed. 🤣

**Comment by fiendish** [comment]
Or they can change their minds...
