### ISSUE TITLE
Consider using pandas_profiling for basic counting

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#296]
I've started using `pandas_profiling`: https://github.com/pandas-profiling/pandas-profiling while writing my extract configs for Chung. It does basic counting and then produces a really nice HTML report. I know this is pretty much what our unique counting functions do too, but what I really like about this is the visual report.  

Here is what a report looks like: 
[2a_dbGaP_SubjectPhenotypesDS cumulative_8.23.18.pdf](https://github.com/kids-first/kf-lib-data-ingest/files/3149180/2a_dbGaP_SubjectPhenotypesDS.cumulative_8.23.18.pdf)

Perhaps our accounting should be refactored to use `pandas_profiling` for basic counting rather than our own counting function? We may still need our own counting functions for relationship counting though.

**Comment by fiendish** [comment]
Please no. The PDF report shown in that link is ugly, hard to scan, and not useful. 

* It doesn't tell when something fails to meet expectations. 
* Visual elements are all over the place.
* There are vertical bar charts without axes and horizontal bar charts with hidden values.
* Mean values are useless.
* Counting zeroes is at best useless and at worst deceptive.
* Warning for high cardinality is terrible.

**Comment by fiendish** [comment]
You mention that there's an HTML report but you gave a PDF. How much of the above is PDF rendering problems vs the report being terrible?

**Comment by allisonheath** [comment]
Yeah my take on it wasn't to use it as-is to generate a PDF, but figured there were underlying functions that could be re-used to generate various stats and counts instead of recoding.

**Comment by znatty22** [comment]
^ What allison said.. I meant maybe we can make use of some underlying counting functions. It definitely doesn't validate counts against expectations. 

I made a PDF of the HTML report bc I GitHub wouldn't let me attach an HTML file

**Comment by znatty22** [comment]
I also liked how the report shows unique counts of different values within columns (e.g. 50 Males, 60 Females, 12 Unknown, 1 unknown for a variable named gender). Maybe we can add that to our count report as well

**Comment by fiendish** [comment]
We definitely can. I think we used to and I removed it because it becomes extremely verbose.

**Comment by fiendish** [comment]
It also completely miscategorizes values. CHD, CNS, and GI being labeled 0 or 1 does not make the field numeric. It's still categorical, but the library's heuristic is naive.
