### ISSUE TITLE
Support non-cartesian product row splitting

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#301]
Our current row splitting operation basically produces a set of rows that reflect the cartesian product of col A and col B. 

This is fine for some situations but I also need a way to turn this: 

| col A | col B |
-------| -----|
|congenital diaphragmatic hernia; Esophageal stricture;  foo| HP:0000776; HP:0002043|

into: 

| col A | col B |
-------| -----|
|congenital diaphragmatic hernia | HP:0000776|
|Esophageal stricture | HP:0002043|
|foo | None |

**Comment by fiendish** [comment]
before you go down this path, can you prove that the order of your codes is the same as the order of your values? Scenarios that I've seen where they do this do not meet that requirement.

**Comment by znatty22** [comment]
Even if it was `congenital diaphragmatic hernia; foo; Esophageal stricture`, then the output table would have an extra row: `Esophageal stricture | None`. Why? Because I do believe that the data contributor very likely tried to order col A and col B properly. They meant for tokens of the split strings in each col, at the same index, to go together. The contributor may have made some mistakes in ordering HPO terms, but oh well. We will see it in the end result and then we can tell them to fix it. 

> I have the same scenario in one of my studies, and the reality is that the relationship between col A and col B does not follow regular rules because the people who made the sheet weren't given sufficient guidance about how to format data so that it can be parsed by a machine.

I agree - It's 100% true. But this is the data I've been given and I want to try to weight the HPO term the contributor gave me vs ones that I lookup. Like I said, to do this I would have to assume the contributor ordered the source text and HPO terms properly in most rows. 

🤷‍♀

**Comment by fiendish** [comment]
> They meant for tokens of the split strings in each col, at the same index, to go together.

This is false. Investigators don't think that way.

**Comment by znatty22** [comment]
They do if they're using the Kids First clinical data spreadsheet bc its shows an example of exactly ^. This original example in my issue is from one of these sheets

**Comment by fiendish** [comment]
If you have "A;B;C" in one column, and "1;2" in another column, even if you assume (and you really can't safely assume this) that the order is completely aligned, you still have no idea whether 1 goes with A or B and whether 2 goes with B or C.

**Comment by fiendish** [comment]
> They do if they're using the Kids First clinical data spreadsheet bc its shows an example of exactly ^. 

This is false. I have data from the same sheet and it does not conform to your expectation.
The Kids First clinical data spreadsheet needs to be redesigned per https://github.com/kids-first/kf-study-imports/issues/552

**Comment by znatty22** [comment]
> If you have "A;B;C" in one column, and "1;2" in another column, even if you assume (and you really can't safely assume this) that the order is completely aligned, you still have no idea whether 1 goes with A or B and whether 2 goes with B or C.

Sure you don't know for sure, but I think its pretty likely so I am making that assumption

**Comment by fiendish** [comment]
Whether the order is likely or not is irrelevant because you don't know where the gaps go.

**Comment by znatty22** [comment]
lol I think they are valid for the data I'm looking at and I don't want to throw out what the investigator gave me if its possible to keep it

**Comment by fiendish** [comment]
The example you gave specifically won't work, though.

My data, for instance, has:

Enchondromas; Vascular malformation | HP:0030038
-- | --

Now without checking, which of the two on the left is described by the one on the right?

**Comment by znatty22** [comment]
Like I said, I am making the assumption for my data that it would be `Enchondromas`

**Comment by fiendish** [comment]
Based on what?

**Comment by fiendish** [comment]
Anyway, like I said, we can figure out how to implement this, but I don't think it should be applied to this specific scenario.
