### ISSUE TITLE
numeric_to_str should turn 0.0 into '0' not '0.0'

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#302]
I expected that [numeric_to_str](https://github.com/kids-first/kf-lib-data-ingest/blob/c206287e0fc4f65d411cbeb97c61b9aaeaad7f0b/kf_lib_data_ingest/common/misc.py#L90) would convert the float `0.0` into the string `'0'` not `'0.0'`, because it turns `1.0` into `'1'`.

Is this the desired behavior? If so, why?

**Comment by fiendish** [comment]
I would classify this as a bug.
