### ISSUE TITLE
S3 utility client for common ingest tasks

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#335]
We need a utility for interacting with S3 and doing common ingest tasks. 

Some features we need:

- Scrape an S3 bucket, prefix and produce an S3 object manifest that will be used in the common s3 object manifest extract config like the one [here](https://github.com/kids-first/kf-ingest-packages/blob/create-SD_46SK55A3/kf_ingest_packages/common/extract_configs/s3_object_info.py
): 
- S3 object tagging

I have a temporary s3 util [here](https://github.com/kids-first/kf-ingest-packages/blob/create-SD_46SK55A3/kf_ingest_packages/common/s3_client.py 
) that needs to be rewritten for production use and moved into ingest library utilities

**Comment by fiendish** [comment]
This one inspects VCFs for embedded KFIDs on the fly https://github.com/kids-first/kf-study-imports/blob/Avi/Avi/utilities/get_s3_tags.py

**Comment by znatty22** [comment]
This has been implemented in https://github.com/d3b-center/d3b-utils-python
