### ISSUE TITLE
Accounting - only count concept instances by ID/UK

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#342]
Post stage run counting is starting to take a while (~5 min). This is mostly due to the fact that the counting is happening for every concept instance and all attributes for a concept. I would like an option to turn on/off "full" counting (concept instances and their descriptive attributes) vs "partial" counting (only concept instances a.k.a attributes that are needed to compose concept `UNIQUE_KEY`s).

So full counting would result in:
```
UNIQUE COUNTS:
{'BIOSPECIMEN_GROUP|ID': 9,
 'BIOSPECIMEN|ANALYTE': 2,
 'BIOSPECIMEN|ID': 16,
 'DIAGNOSIS|TARGET_SERVICE_ID': 1,
 'FAMILY|ID': 3,
 'GENOMIC_FILE|HARMONIZED': 1,
 'GENOMIC_FILE|HASH_DICT': 16,
 'GENOMIC_FILE|ID': 9,
 'GENOMIC_FILE|SIZE': 1,
 'GENOMIC_FILE|URL_LIST': 1,
 'PARTICIPANT|FATHER_ID': 4,
 'PARTICIPANT|GENDER': 3,
 'PARTICIPANT|HIDDEN': 1,
 'PARTICIPANT|ID': 9,
 'PARTICIPANT|MOTHER_ID': 4,
 'PARTICIPANT|VISIBLE': 1,
 'PHENOTYPE|EVENT_AGE_DAYS': 8,
 'PHENOTYPE|NAME': 3,
 'PHENOTYPE|OBSERVED': 2,
 'SEQUENCING|CENTER|TARGET_SERVICE_ID': 1}
```

while partial counting would result in:
```
UNIQUE COUNTS:
{'BIOSPECIMEN_GROUP|ID': 9,
 'BIOSPECIMEN|ID': 16,
 'FAMILY|ID': 3,
 'GENOMIC_FILE|ID': 9,
 'PARTICIPANT|ID': 9,
 'PHENOTYPE|EVENT_AGE_DAYS': 8,
 'PHENOTYPE|NAME': 3,
 'PHENOTYPE|OBSERVED': 2}
```

I tried this and it worked pretty well. Here is a before and after example for the Chung study (\~2300 participants/specimens, \~4000 files). In this case transform stage exec time went from \~7 min to \~1 min. See below:

```
BEFORE:

2019-06-17 14:06:03,079 - GuidedTransformStage - INFO - Doing concept discovery for default DataFrame in transform function output
744 2019-06-17 14:11:45,091 - GuidedTransformStage - INFO - Done counting what we got
745 2019-06-17 14:11:45,093 - GuidedTransformStage - DEBUG - Writing discovered counts to /Users/singhn4/Projects/kids_first/kf-ingest-pack      ages/kf_ingest_packages/packages/SD_46SK55A3/output/TransformStage_concept_discovery.json
746 2019-06-17 14:12:51,570 - GuidedTransformStage - INFO - END GuidedTransformStage. Time elapsed: Sec: 10.184616088867188 Min: 7.0 Hours:       0.0
747 2019-06-17 14:12:51,574 - GuidedTransformStage - INFO - Begin Basic Stage Output Validation
748 2019-06-17 14:12:59,106 - GuidedTransformStage - INFO - End Basic Stage Output Validation

AFTER:

2019-06-18 11:26:57,328 - GuidedTransformStage - INFO - Doing concept discovery for default DataFrame in transform function output
2019-06-18 11:27:43,812 - GuidedTransformStage - INFO - Done counting what we got
2019-06-18 11:27:43,812 - GuidedTransformStage - DEBUG - Writing discovered counts to /Users/singhn4/Projects/kids_first/kf-ingest-packages/kf_ingest_packages/packages/SD_46SK55A3/output/TransformStage_concept_discovery.json
2019-06-18 11:27:56,417 - GuidedTransformStage - INFO - END GuidedTransformStage. Time elapsed: Sec: 25.209589958190918 Min: 1.0 Hours: 0.0
2019-06-18 11:27:56,418 - GuidedTransformStage - INFO - Begin Basic Stage Output Validation
2019-06-18 11:27:56,620 - GuidedTransformStage - INFO - End Basic Stage Output Validation
```

**Comment by fiendish** [comment]
√

**Comment by fiendish** [comment]
The problem with this is that you then can't compare the outputs of stages for consistency.

**Comment by znatty22** [comment]
> The problem with this is that you then can't compare the outputs of stages for consistency.

I don't think I understand. Can you give me an example?

**Comment by fiendish** [comment]
There are two kinds of tests:

1. Did we get the right number of things? 
2. Did we screw up the values somehow while transforming?

**Comment by znatty22** [comment]
Oh I see, and you're saying that if we implement this, we don't get 2. Is that right?

**Comment by fiendish** [comment]
yeah

**Comment by fiendish** [comment]
I'm sure we're doing extra work and can speed this up a lot. We just need to make sure that 2 doesn't get lost in the process.

**Comment by znatty22** [comment]
> We just need to make sure that 2 doesn't get lost in the process.

If we make this a switch that can be turned on or off then 2 won't get lost completely. I understand that puts us at risk of having inconsistent accounting outputs between two runs where one had the switch "on" vs "off". But i think its useful to have this option bc a lot of times (while dev/debugging) I just want to run extraction with basic counting. 

...Although if we _can_ optimize accounting enough then maybe it won't matter bc it'll be fast enough that we don't need to turn anything on or off?
