### ISSUE TITLE
dict keys going into transform function should be relative to study dir, not full path

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#354]
Using the full path makes it so that the keys can't be referenced during transform without either string processing or knowing specific environmental conditions that can't be known during configuration. Since all of the extract configs are in the extract config directory, there's no real reason to include path components outside of that.

**Comment by znatty22** [comment]
I think originally, wayyy back in the day, we thought extract configs could potentially be in different directories. I don't know if anyone would actually want do that though. I guess maybe if you had a lot of extract configs and wanted to organize them into multiple directories you would 🤷‍♀ 

Maybe we could make the key `<directory folder name>/<filename>`? 

> knowing specific environmental conditions that can't be known during configuration. 
Also, what did you mean by that ^

**Comment by fiendish** [comment]
> knowing specific environmental conditions that can't be known during configuration.
Also, what did you mean by that ^

Person writing config doesn't know what anything outside the study directory will look like.

**Comment by znatty22** [comment]
I'm still confused. Why do they need to know anything outside the study directory? And when you say person writing config are you talking about the transform module? Maybe we can talk in person

**Comment by fiendish** [comment]
> Why do they need to know anything outside the study directory?

Because right now the keys are paths starting all the way from /

**Comment by fiendish** [comment]
> I think originally, wayyy back in the day, we thought extract configs could potentially be in different directories

Nothing in the code supports that currently

**Comment by znatty22** [comment]
Hmm that makes sense to me. The person/people writing the extract configs and transform modules should know where they put their files. I don't see this as unreasonable. 

I'm not sure that we really need this change? As far as I can see all this is really doing is removing one small inconvenience from the transform module (processing the paths to get the filenames). 

Also, if we make this change, then any logs for transform will show file names and not file paths. That might be confusing if you've organized your extract configs into multiple dirs and have files with the same name.

**Comment by fiendish** [comment]
> Hmm that makes sense to me

It shouldn't. 

> The person/people writing the extract configs and transform modules should know where they put their files.

They don't know the full disk hierarchy _OUTSIDE of their study folder_ on whatever random system their study is being run.

> As far as I can see all this is really doing is removing one small inconvenience from the transform module

That everyone always has to do every single time because there's literally no alternative.

**Comment by fiendish** [comment]
> logs for transform will show file names and not file paths

See amended issue title

**Comment by fiendish** [comment]
> if you've organized your extract configs into multiple dirs

The code doesn't support doing this

**Comment by fiendish** [comment]
It does now in ffde6c4
