### ISSUE TITLE
Fix extract read_output bug

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#367]
If ingest is run with a subset of stages (e.g. t), it reads in the previous stages output from disk. When pandas.read_csv is used to read in the output, it rounds floats in a weird way. This later causes failures in accounting when comparing extract stage and transform stage uniques:

See: 
![image](https://user-images.githubusercontent.com/10283712/61813541-e7ea1480-ae13-11e9-88bd-d20e61b71d79.png)

This can be fixed by supplying pandas.read_csv with`float_precision='round_trip'`. See 
https://stackoverflow.com/questions/47368296/pandas-read-csv-file-with-float-values-results-in-weird-rounding-and-decimal-dig or by setting `dtype=object`

To implement this fix, we should ensure that all calls to pandas.read_csv use this keyword arg. To do this in a DRY way, maybe we can factor out the pandas read from disk functionality in extract stage's `_source_to_df` function (call it `pandas_safe_read`?). Then this function can be used anywhere in the code.  See #368

**Comment by znatty22** [comment]
Thoughts @fiendish?

**Comment by znatty22** [comment]
Or I guess we could always read data in with `dtype=object`

**Comment by fiendish** [comment]
> Or I guess we could always read data in with dtype=object
 
√
