### ISSUE TITLE
extract configs can't use the designated auth configs

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#373]
auth_configs is passed in at FileRetriever initialization, so out of stream modules like extract config files don't know which auth_configs to use.

**Comment by znatty22** [comment]
Can you give an example of when we would use this?

**Comment by fiendish** [comment]
Sometimes to extract data from one file you also need access to another file.

**Comment by znatty22** [comment]
Does that other file have column info or config info that you're dynamically looking up to be able to read/process data from the source file targeted by the extract config?

**Comment by fiendish** [comment]
yes

**Comment by znatty22** [comment]
Maybe I'm still not understanding the problem. Couldn't you just do this in your extract config:
```
auth_config = {'url_pattern': {
    'type': 'token',
    'token_location': 'header',
    'token': 'my token'
}}
f = FileRetriever(auth_configs=auth_configs).get(<url>)
```

**Comment by fiendish** [comment]
Auth config depends on deployment mode, so no.

**Comment by znatty22** [comment]
Ah I see so you're not just trying to use FileRetriever with some random auth config. You want to use the FileRetriever with the deployment mode auth configs so that you can fetch other files from study creator. Is that right?

**Comment by fiendish** [comment]
Correct
