### ISSUE TITLE
Document Persistence to Warehouse

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#413]
Most important part of this is to include a diagram to illustrate how data is organized in the Warehouse. The consensus was: 

- Each study will have its own database
- Inside a study's database, each stage's output tables will be persisted to its own schema

**Comment by znatty22** [comment]
This is part of https://github.com/d3b-center/clinical-data-flow/issues/2

**Comment by fiendish** [comment]
this was closed by #425
