### ISSUE TITLE
Broken link in extract stage of tutorial

### ISSUE THREAD

**Issue by gsantia** [kids-first/kf-lib-data-ingest#428]
the URL here:

https://github.com/kids-first/kf-lib-data-ingest/blob/30496ff93ede7e86d28540360684a19ad812c6c0/docs/source/tutorial/extract/extract_example.inc#L59

**Comment by fiendish** [comment]
That's not a broken link though?

**Comment by fiendish** [comment]
Oh it is, lol, nvm
