### ISSUE TITLE
Bugs on testing your ingest package page

### ISSUE THREAD

**Issue by gsantia** [kids-first/kf-lib-data-ingest#430]
1) [here](https://kids-first.github.io/kf-lib-data-ingest/tutorial/package_testing.html#set-expected-counts)

After changing the counts as shown in the tutorial, the counts still fail

2) [here](https://kids-first.github.io/kf-lib-data-ingest/tutorial/package_testing.html#user-defined-tests)

Page says 'This test validates that there are exactly 2 duo-type families and 1 trio-type family.', this doesn't match the actual test

**Comment by fiendish** [comment]
what should they be instead?

**Comment by gsantia** [comment]
for the counts, gives this in the log for the transform stage:
```
EXPECTED COUNT CHECKS:
 +----------------+------------+---------+---------+
 | Key            |   Expected |   Found | Equal   |
 |----------------+------------+---------+---------|
 | FAMILY|ID      |          2 |       2 | ✅       |
 | PARTICIPANT|ID |          9 |       5 | ❌       |
 | BIOSPECIMEN|ID |         16 |      10 | ❌       |
 +----------------+------------+---------+---------+
```

**Comment by fiendish** [comment]
recommended change?
