### ISSUE TITLE
Transform function in tutorial results in exception

### ISSUE THREAD

**Issue by gsantia** [kids-first/kf-lib-data-ingest#431]
After you comment out the block in the transform module and run the test, results in a merge collision

**Comment by fiendish** [comment]
where's that?

**Comment by gsantia** [comment]
https://kids-first.github.io/kf-lib-data-ingest/tutorial/transform.html#guided-transform-module

i think this is the cause of the [counts issue](https://github.com/kids-first/kf-lib-data-ingest/issues/430)
