### ISSUE TITLE
Refactor UK generation with modular message packing and sending

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#444]
* Replace UK generation with drastically simpler on-send mechanism.
* Merge target service api and message packer.
* Modularize get/patch/post mechanism in loader according to service definition.

This should resolve #194, obsolete #179, and answer #341

https://github.com/d3b-center/clinical-data-flow/issues/17
https://github.com/d3b-center/clinical-data-flow/issues/22

**Comment by fiendish** [comment]
I think this about summarizes what I want to do. [ingest_load_refactor.pdf](https://github.com/d3b-center/clinical-data-flow/files/4344861/ingest_load_refactor.pdf)

# Overview

We start with extracted and joined CONCEPTs.

We want to produce target entity payloads.

We want to use the same unique identifier whenever we encounter the same target entity.

Therefore, we want a lookup that maps the uniquely identifying components of a target entity to its synthetic identifier. We call the text composition of those uniquely identifying components a "unique key". `our_lookup(unique_key)` should return a unique target service identifier (KFID).

# Current approach

## Components `target_apis/kids_first.py` (interpreted configuration) and `etl/load/message_packer.py` (interpretive code) and `etl/load/load.py` (interpretive code)

(nb. The current approach requires all components to be understood together simultaneously)

---

<https://github.com/kids-first/kf-lib-data-ingest/blob/fb55890f469b4d755e2862e132538fcff7d30de1/kf_lib_data_ingest/target_apis/kids_first.py>

### 1. Target API configuration (interpreted by code) defined as a dict with service properties as keys and extracted CONCEPTs as values

Looks like:

  ```Python
  target_concepts = {
      "diagnosis": {
          "standard_concept": CONCEPT.DIAGNOSIS,
          "endpoint": "/diagnoses",
          "properties": {
              target_service_entity_id: CONCEPT.DIAGNOSIS.TARGET_SERVICE_ID,
              "participant_id": CONCEPT.PARTICIPANT.TARGET_SERVICE_ID,
              "external_id": CONCEPT.DIAGNOSIS.UNIQUE_KEY,
              ...
          },
          "links": [
              {
                  "target_attribute": "participant_id",
                  "standard_concept": CONCEPT.PARTICIPANT,
                  "target_concept": "participant"
              }
          ]
      },
      ...
  }
  ```

Major Flaws:

* Extraneous and misleading components like top level "standard_concept". In fact the target API is not supposed to relate 1:1 to an extracted CONCEPT class.

* "properties" section only capable of configuring a flat entity structure (simple keys and values) without any inner nesting complexity.

* "links" section clearly geared only for current dataservice schema with flat (simple keys and values) connections to other target entities.

* "links" section doubles down on the conflation between target entities and extracted CONCEPT classes by referring to a "standard_concept" for the link.

* Structure format is just arcane enough to require a custom validation routine to make sure that it wasn't screwed up:

  ```Python
  def validate():
    """Custom validation specific to this target api config"""
    for target_concept, schema in target_concepts.items():
    ...
  ```

---

### 2. Unique key composition configuration (interpreted by code) defined as a dict with extracted CONCEPT names as keys with associated required/optional extracted CONCEPTs as values

Looks like:

  ```Python
  identifiers = {}
  identifiers[CONCEPT.DIAGNOSIS._CONCEPT_NAME] = {
      "required": [CONCEPT.PARTICIPANT.UNIQUE_KEY, CONCEPT.DIAGNOSIS.NAME],
      "optional": [CONCEPT.DIAGNOSIS.EVENT_AGE_DAYS],
  }
  ...
  ```

Major Flaws:

* This model applies unique key compositions to extracted CONCEPT classes, when logically the unique keys are supposed to identify target service entities _not_ extracted CONCEPTs. In essence, it furthers the harmful assumption of a 1:1 relationship between the two.

* Does not accommodate alternative identifiers. Some target entities can be uniquely identified in multiple ways while you only need to know one. Example: a sequencing experiment may have its own unique ID and also a unique library ID or only one of them.

---

### 3. Interpretive code

* Hundreds of lines of code with even more comments (necessary because of complexity) in `message_packer.py` to procedurally apply the contents of `target_apis/kids_first.py` to the extracted and joined data and turn it into something that isn't even the final product.

  <https://github.com/kids-first/kf-lib-data-ingest/blob/fb55890f469b4d755e2862e132538fcff7d30de1/kf_lib_data_ingest/etl/load/message_packer.py>

  * def _standard_to_target
  * def _insert_unique_keys
  * def _add_unique_key_cols
  * def _unique_key_cols

  Keys are all computed ahead of time even though some depend on others (a diagnosis entry is in-part identified by the person being diagnosed). When one references another, the code must go deeper (like inception!).

* Then dozens more lines in `etl/load/load.py` to finish the job:

  <https://github.com/kids-first/kf-lib-data-ingest/blob/fb55890f469b4d755e2862e132538fcff7d30de1/kf_lib_data_ingest/etl/load/load.py#L303-L321>

  * def _apply_property_value_transformations

  <https://github.com/kids-first/kf-lib-data-ingest/blob/fb55890f469b4d755e2862e132538fcff7d30de1/kf_lib_data_ingest/etl/load/load.py#L341-L369>

  * half of def _load_entity

Major Flaws:

* Inflexibly assumes a flat target entity structure (as above). So likely not expandable without a complete rewrite anyway.

* Deeply nested and recursive logic and uses argument references instead of returns to accumulate hidden side effects, so it's hard to understand and debug.

  * See embedded calls to `self._unique_key_cols` @
    * <https://github.com/kids-first/kf-lib-data-ingest/blob/fb55890f469b4d755e2862e132538fcff7d30de1/kf_lib_data_ingest/etl/load/message_packer.py#L582>
    * <https://github.com/kids-first/kf-lib-data-ingest/blob/fb55890f469b4d755e2862e132538fcff7d30de1/kf_lib_data_ingest/etl/load/message_packer.py#L725>

# Proposed approach

Proposal:

Compose our unique keys on the fly instead of all up-front. Since we can cache
returned target service identifiers (or whatever) as we submit, we don't need
to do any complex recursive logic to compose unique keys; we just look at the
data currently available.

We would replace the bulk message builder with one-at-a-time building.

---

For brevity we resort to stub code here.

```Python
def join(*args):
  return '.'.join([str(a) for a in args])

# defined for each API
def submit_to_target_service(*args):
  # PUT/POST/Whatever
  pass

# these replace the current unique key configuration and interpretive code
def make_patient_key(row):
  return join(row["A"], row["B"], ...)

def make_specimen_key(row):
  return join(row["X"], row["Y"], ...)

# this is basically the FHIR payload functions that Meen and I just built
# but with some small upgrades
# they replace the current API configuration and interpretive code
def build_specimen(row, target_id_cache):
  unique_key = make_specimen_key(row)
  specimen = { 
    "X": row["X"],
    "Patient": target_id_cache["Patient"][make_patient_key(row)],
    ...
  }
  return specimen, unique_key


target_lookup = {
  "Specimen": {
    "endpoint": "/make_a_specimen",
    "builder": build_specimen
  },
  ...
}

target_id_cache = {}  # this will get uploaded to a server somewhere

# loader code
for target_type in all_target_types:  # ordered by dependency requirements
  endpoint = target_lookup[target_type]["endpoint"]
  builder = target_lookup[target_type]["builder"]
  df = transform_output.get(target_type) or transform_output.get("default")
  assert df is not None

  for _, row in df.iterrows():
    payload, unique_key = builder(row, target_id_cache)
    if payload and unique_key and (unique_key not in target_id_cache):
      target_service_id = submit_to_target_service(endpoint, payload)
      target_id_cache[unique_key] = target_service_id
```

### Premises

* Target entities get loaded in the order that satisfies dependencies. If specimens need to reference patients, then patients get loaded first.

* The values needed to compose any required unique keys within a builder function must necessarily be available in the input data, otherwise the input data is invalid.

* Code is maximally flexible vs configuration.

### Construction Rules

* Two functions define each target entity.
  1. Unique key composer from a set (dataframe row) of data.

  2. Payload builder from a set (dataframe row) of data.

* Unique keys are generated as-needed purely for the purpose of caching target service IDs and for no other reason.

**Comment by znatty22** [comment]
@fiendish Seems pretty straight forward. 1) UKs are generated from target payloads now 2) Code over configuration 3) Custom logic per target API is all encapsulated in the message packer/builder functions whatever it's called 

It sounds fine to me. I'll probably have more feedback once a PR is out for the code changes.  

Looks good to start 💻 🤓
