### ISSUE TITLE
missing psycopg2 req?

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#449]
It looks like the sqlalchemy dep doesn't also install psycopg2?

**Comment by znatty22** [comment]
Oh hmm yea i think i ran into this before. We have to add that to the requirements.txt

**Comment by fiendish** [comment]
I think it's a bit more complicated than that. psycopg2 doesn't install easily on macos with pip.

**Comment by znatty22** [comment]
Oh ugh...thats right, you need the binary version or something? Maybe we should just add this to the install page of the docs?
