### ISSUE TITLE
Fix kf-lib-data-ingest python package distribution

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#456]
The `kf-lib-data-ingest` Python package is missing a bunch of `__init__.py` files in its subpackages, causing the top level package to not install correctly. 

We missed this before because we were always using `pip install -e .` (install as editable) rather than `pip install .` See https://stackoverflow.com/questions/57157343/why-do-packages-installed-with-pip-install-e-not-need-init-py for details. 

Additionally, we were not including necessary non-Python files in our distribution such as our template ingest package (`kf-lib-data-ingest/templates`). 

We need to fix both issues to make `kf-lib-data-ingest` install properly.

**Comment by gsantia** [comment]
These missing `__init__.py` files also makes the use the Sphinx auto-documentation feature much harder to use, which is a problem I ran into before. The plugin by default only builds documentation pages for complete modules.
