### ISSUE TITLE
Define attribute validation test inputs

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#479]
Need a standard structure that defines what the allowable values are for each attribute that will be validated.

For example, how will we represent this?
Patient gender can only take on values: Female, Male, Other

See https://github.com/kids-first/kf-lib-data-ingest/blob/master/kf_lib_data_ingest/common/constants.py
Also see Dataservice schema.py files for each endpoint: https://github.com/kids-first/kf-api-dataservice/blob/master/dataservice/api/biospecimen/schemas.py

**Comment by fiendish** [comment]
I'm thinking something like
```Python
{
  CONCEPT.PARTICIPANT.RACE: {constants.RACE.WHITE, constants.RACE.NATIVE_AMERICAN, constants.RACE.BLACK, constants.RACE.ASIAN, constants.RACE.PACIFIC, constants.COMMON.OTHER},
  CONCEPT.PARTICIPANT.ENROLLMENT_AGE_DAYS: lambda x: (int(x) >= 0) and (int(x) < 43800),
  ...
}
```
where the values are either a set of enumerated values or a function that takes one argument and returns whether the value is good or not

**Comment by znatty22** [comment]
@fiendish I see what you were saying about having values or lambdas - I like it, that makes it very flexible.

**Comment by gsantia** [comment]
Could also do
```
{
  CONCEPT.PARTICIPANT.RACE: lambda x: x in {constants.RACE.WHITE, constants.RACE.NATIVE_AMERICAN, constants.RACE.BLACK, constants.RACE.ASIAN, constants.RACE.PACIFIC, constants.COMMON.OTHER},
  CONCEPT.PARTICIPANT.ENROLLMENT_AGE_DAYS: lambda x: (int(x) >= 0) and (int(x) < 43800),
  ...
}
```

for the sake of uniformity
