### ISSUE TITLE
Newbie: feedback on quickstart. 

### ISSUE THREAD

**Issue by bwalsh** [kids-first/kf-lib-data-ingest#503]
Kicking the tires, learning about data ingest package.
Ran into this when running quick start.

FileNotFoundError: [Errno 2] No such file or directory: '/Users/walsbr/kf-model-fhir/my_study/data/clinical.tsv'

![image](https://user-images.githubusercontent.com/47808/93902491-71150980-fcac-11ea-87ef-5b92b6a24be0.png)

I browsed the repo, found a copy of clinical.tsv, placed it in  my_study/data/clinical.tsv and then was able to proceed.

**Comment by fiendish** [comment]
I think this was fixed in https://github.com/kids-first/kf-lib-data-ingest/pull/455 ?
