### ISSUE TITLE
Operation: split rows into multiple rows

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#53]
Would be nice to have a helper function to split rows into multiple rows based on comma separated values occurring in a column of choice. 

For example, Onel 2015 has a lot of data like this: 

| tumor_location_uberon | foo |
| ----------------------- | ----|
| UBERON:0002168, UBERON:0002167, UBERON:0003728 | A

I want a function/operation that does:
```python
def split_rows(df, col, delimiter):
    # split rows with delimited string into individual rows
    return new_df

new_df = split_rows(df, 'tumor_location_uberon', ',')
```
and results in:

| tumor_location_uberon | foo |
| ----------------------- | ---- |
| UBERON:0002168 | A
| UBERON:0002167 | A
| UBERON:0003728 | A

**Comment by fiendish** [comment]
If you value_map to a list of values instead of just a value, then the list will get split up into multiple rows.
