### ISSUE TITLE
Outside suggestion: extract operations conditional on applicability (e.g. in_col existence)

### ISSUE THREAD

**Issue by fiendish** [kids-first/kf-lib-data-ingest#579]
Does anyone have any thoughts on whether this is a fundamentally good thing or bad thing for the ingest library to include?

---

There has been a request from the data tracker team for extract operations to be skipped without error (or at least not raise an uncaught exception) if conditions make them inapplicable so that the same set of operations can be reused for files with different subsets of known _optional_ columns.

I definitely don't want extract to continue after other errors, so if this is implemented I think it would require applicability checking in each operation.

Ignoring df and row maps that operate on entire frames and constant map that operates without a reference, the remaining global operations are:

**value**
potential condition: in_col exists

**column**
potential condition: in_col exists

**keep**
potential condition: in_col exists

**melt**
potential condition: _all_ map_for_vars columns exist

---

**The obvious benefit** is the ability to use static predefined configurations for files with different column subsets without having to dynamically generate the operations lists. 

**The obvious problem** is that skipping over invalid entries will make it easier to miss and thus harder to debug invalid configurations. 

Possible mitigation strategies for this concern:

* Add another argument to those operations to designate them as explicitly "optional" and only allow skipping them if set to True.
* Logging `warning` level messages when skipping an operation for invalidity.
* Including the skipped operations and the reasons for skipping them in the final run output.

**The obvious alternative** is for the data tracker to compose operations list dynamically and not depend on the proposed behavior.

**Comment by znatty22** [comment]
@fiendish I'm not sure I'm understanding this issue completely. Let me see if I got this right. 

Say we have a participant demographics data file. We want a static extract config that we can use on this data file and various flavors of this file, where the differences would be some optional columns that may be present in some participant demographics files but not others. Correct?

Then you're also asking, how do we want to process these optional columns. Do we assume a column specified in the extract config but not present in the data is an optional column that should be skipped? If we do that then how will we distinguish between a user / data file error and a truly optional column? That's the concern - correct?

If I got all that right, then I think I like mitigation strategies / bullets 1 and 2. I don't understand what bullet 3 means

**Comment by fiendish** [comment]
> Say we have a participant demographics data file. We want a static extract config that we can use on this data file and various flavors of this file, where the differences would be some optional columns that may be present in some participant demographics files but not others. Correct?

Correct.

> Then you're also asking, how do we want to process these optional columns. Do we assume a column specified in the extract config but not present in the data is an optional column that should be skipped? If we do that then how will we distinguish between a user / data file error and a truly optional column? That's the concern - correct?

Correct.

>  I don't understand what bullet 3 means

So right end where we basically say "All done! Here are your report files!" (or whatever). We could add special extra messages there too if things were skipped over to say "You should know that all the way back at the beginning we skipped some stuff" just because those early messages fly by so quickly.

**Comment by znatty22** [comment]
Hmm yea I like the log messages and we should use the warn emoji to make them stand out haha. I find that even with logging stuff at the end its sometimes still easy to overlook
