### ISSUE TITLE
file retriever s3 save fails on first invalid credentials

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#85]
_s3_save will cycle through the available profiles in a ~/.aws/credentials file,  and try each one until it finds one that works or raise an exception if it can't find one. 

If you have multiple profiles in your credentials file, _s3_save may potentially try one that fails authentication. This raises a `botocore.exceptions.ClientError`. Should probably change the method to catch both `botocore.exceptions.NoCredentialsError` and `botocore.exceptions.ClientError`.

Unfortunately the `botocore.exceptions.ClientError` isn't very descriptive. It just has a 400 status code with a Bad Request message. It would have been nicer to catch `botocore.exceptions.ClientError` and if we know its an auth failure, then we pass the exception so _s3_save may keep trying credentials.

**Comment by fiendish** [comment]
expected behavior?
