### ISSUE TITLE
Modify installation of kf-lib-data-ingest so that it has better namespace

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#87]
**Problem**
Currently when you install the kf-lib-data-ingest lib, the src/ is add to sys path and everything under that directory is made available for import. If you want to use this as an actual library, this is problematic since the modules in the src/ dir are named very generically. 

For example, I want to use the kf-lib-data-ingest etl.extract package in my OMOP ETL code
```
.
├── code
│   ├── extract.py
│   ├── load.py
│   ├── etl.py
│   └── transform.py
```
```python
# My extract.py file
from etl.extract.extract import ExtractStage
def run(output_dir, extract_configs):
    es = ExtractStage(output_dir, extract_configs)
    df_out = es.run()
    es._write_output(df_out)

    return df_out
```
But I get namespace collisions with my etl.py module

**Solution**
Change setup.py to find packages in the top level repo dir rather than the src dir. Imports will then become: 

```python
from kf_lib_data_ingest.etl.extract import ExtractStage
```

**Comment by fiendish** [comment]
👌
