### ISSUE TITLE
Move concept_schema.py into a higher level package

### ISSUE THREAD

**Issue by znatty22** [kids-first/kf-lib-data-ingest#89]
I think concept_schema.py is burried too far in the kf_lib_data_ingest package tree. We use it frequently in the lib itself and outside the lib in our extract configs, so its not really just a transform stage thing.

We should probably move it to `kf_lib_data_ingest.common` or even `kf_lib_data_ingest`. Should do this in a separate PR after merging in #57

**Comment by fiendish** [comment]
agree

**Comment by znatty22** [comment]
Update all refs in docs too
